### ISSUE TITLE
AutoGridView seems to resize incorrect views after scrolling

### ISSUE THREAD

**Issue by diceroll123** [JJdeGroot/AutoGridView#1]
I'm so glad this exists, first off! This issue being fixed would make it perfect though! :+1:

I thought it was an issue with my ViewHolder (and the way I use it) at first, but besides setting the text & lines in TextViews and the Gravity of the TextView, it doesn't do anything.

I have a bunch of placeholders, all but one of them are single-line strings. I have my code highlight the one multi-line string to have a red background.

![2015-09-11_17-28-54](https://cloud.githubusercontent.com/assets/1243957/9826969/0e3a553a-58ac-11e5-9a02-a90c60dc04e1.png)

If it's any use, here's the part of the code that stretches height of the views...

```
viewHolder.emoticon.setText(mItems[position]);
viewHolder.emoticon.setLines(1);
viewHolder.emoticon.setSingleLine(true);

if(mItems[position].contains("\n")) {
    viewHolder.emoticon.setLines(0);
    viewHolder.emoticon.setSingleLine(false);
    cardview.setCardBackgroundColor(Color.parseColor("#FF0000"));
}
```

I did the highlighting to make sure my code didn't mistakenly make one of the later increased-height views red. As you can see in the picture below, nothing but the height is changed.

From the first picture, all looks well, but... I scroll down a little (there's not too many placeholders...) and this is at the bottom.

![2015-09-11_17-29-26](https://cloud.githubusercontent.com/assets/1243957/9826976/17f9ed4c-58ac-11e5-9b5f-acf38f557753.png)

_and then scrolling up and down more only makes the resize happen on one or more different rows_, though the row with the red view is still correctly sized! :smile:

Possibly useful note:
- Changing the layout back to GridView (_though I don't want to use a regular one_) correctly highlights red as well, and it clips on that one, as expected since the height doesn't change.

I've fiddled with the AGV code a bit but I'd like to think I have no idea what I'm doing because I only made the issue worse, then undid my changes. :disappointed: 

**EDIT:** ~~another note: using one column ("list" mode) works fine.~~ nvm, same issue. D:

**Comment by JJdeGroot** [comment]
Hi, thanks for the report.

Google has also released the [StaggeredGridLayoutManager](https://developer.android.com/reference/android/support/v7/widget/StaggeredGridLayoutManager.html) in the meantime. You won't experience any overlap when using that LayoutManager, but your grid will look, as the name does suggest, staggered.

I will take a look at the code in the near-future and see if I can resolve some of the issues that have been mentioned.

**Comment by diceroll123** [comment]
Ahh, glad to hear you'll try to get that fixed! :grinning: 

As for the Staggered Grid, I tried it but I'm not a huge fan of the lack of fast-scroll support for RecyclerView. Perhaps when RecyclerView is more refined. Also the whole...staggered look isn't very pretty. :stuck_out_tongue: 

For now I'll see what I can do though. Thanks!
