### ISSUE TITLE
obduro.nl/blog/the-solution-of-android-gridview-overlap/ doesn't exists anymore

### ISSUE THREAD

**Issue by LysonLuo** [JJdeGroot/AutoGridView#2]
it seems the blog "http://obduro.nl/blog/the-solution-of-android-gridview-overlap/" doesn't exists anymore ?

**Comment by JJdeGroot** [comment]
Yes, correct. I will place the blog in the readme of this project ASAP.
Edit: Blog has been added to the readme.
