### ISSUE TITLE
Android “Only the original thread that created a view hierarchy can touch its views.”

### ISSUE THREAD

**Issue by dineshmm23** [JJdeGroot/AutoGridView#5]
`@Override
   ```
 public void setNumColumns(int numColumns) {
        this.numColumns = numColumns;
        super.setNumColumns(numColumns);
        Handler mHandler = new Handler(Looper.getMainLooper()) {
            @Override
            public void handleMessage(Message message) {
                // This is where you do your work in the UI thread.
                // Your worker tells you in the message what to do.
                Log.d(TAG, "setSelection --> " + previousFirstVisible);
                setSelection(previousFirstVisible);
            }
        };

    }
````

`Fixed` by running on `ui thread`.

`Error` found at  setSelection(previousFirstVisible);
`Log` Showed :: setSelection -->0

**Comment by JJdeGroot** [comment]
Hi, you can run it on the main thread from inside the setNumColumns method. But it would be better to make the code that makes this call in your Fragment or Activity run on the main thread.

See also: https://stackoverflow.com/questions/18656813/android-only-the-original-thread-that-created-a-view-hierarchy-can-touch-its-vi
