### ISSUE TITLE
Error: Unable to update columns caused at runtime

### ISSUE THREAD

**Issue by dineshmm23** [JJdeGroot/AutoGridView#6]
It happened  to me when i was closing application.
   `App not responding`

1> What cloud be the reason for below error?
2>Is it bug related to my application?
3>If not, can u help me .

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                         Process: com.entriver.tjmskorkast, PID: 6788
>                                                                         android.content.res.Resources$NotFoundException: Resource ID #0x0
>                                                                             at android.content.res.Resources.getValue(Resources.java:1457)
>                                                                             at android.content.res.Resources.getInteger(Resources.java:1171)
>                                                                             at com.entriver.tjmskorkast.utils.AutoGridView.updateColumns(**AutoGridView.java:65**)
>                                                                             at com.entriver.tjmskorkast.utils.AutoGridView.onConfigurationChanged(**AutoGridView.java:92**)
>                                                                             at android.view.View.dispatchConfigurationChanged(View.java:9002)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1199)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1203)
>                                                                             at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:3470)
>                                                                             at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3616)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
>                                                                             at android.os.Looper.loop(Looper.java:194)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5624)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
>

**Comment by JJdeGroot** [comment]
Hi,
The app crashes because it cannot read the amount of columns integer from your resources.

Example: ```android:numColumns="@integer/grid_columns"```
You need to add the integer constant to your resources folder.

See also here: https://stackoverflow.com/questions/19297522/android-integer-from-xml-resource

**Comment by dineshmm23** [comment]
yes, that works only if `android:numColumns="@integer/grid_columns"` is done `hardcoded`.
But i wanted to it `dynamically` set the `numColumns`. Like this`-->`

```
private void createGridViews(ArrayList<ModelGridView> gridViews) {
        for (int i = 0; i < gridViews.size(); i++) {
              final ModelGridView mgv = gridViews.get(i);
              ArrayList<ModelGridViewElement> gridElements = mgv.getGridViewElements(); 
              AutoGridView gridView = new AutoGridView(getActivity());
             gridView.setNumColumns(mgv.getColumns());
              gridView.setBackgroundColor(Color.WHITE);
              gridView.setLayoutParams(new PercentRelativeLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT));
            percentRelativeLayout.addView(gridView);
      }
}
```

**Comment by JJdeGroot** [comment]
In that case you would need to change the ```updateColumns``` method because it assumes a hardcoded constant is used.

```
private void updateColumns() {
  this.numColumns = getContext().getResources().getInteger(numColumnsID);
}
```
This method is called upon orientation change e.g. portrait to landscape because you might want to display more columns in landscape orientation. In your case this results in a crash because the numColumnsId is undefined/invalid.

Just leave the method blank and use the setColumn method to dynamically set the amount of columns.
